on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'profile.test.sql'
          username: ''
          password: ''
          url: 'jdbc:postgresql://localhost/template1'
          referenceUrl: 'jdbc:postgresql://localhost/template1'
          name: Build and Test
